/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Community;
import model.CommunityDirectory;
import model.Hospital;
import model.HospitalDirectory;

/**
 *
 * @author manikantareddythikkavarapu
 */
public class CreateCommunityAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCommunityAdminPanel
     */
    HospitalDirectory hospitalDirectory;
    Hospital hospital;

    public CreateCommunityAdminPanel(HospitalDirectory hospitalDirectory) {
        initComponents();
        this.hospitalDirectory = hospitalDirectory;
    }

    public CreateCommunityAdminPanel(HospitalDirectory hospitalDirectory, Hospital hospital) {
        initComponents();
        this.hospitalDirectory = hospitalDirectory;
        this.hospital = hospital;
        setSysAdminCreateCommunityPanel();
    }

    public CreateCommunityAdminPanel() {
        initComponents();
    }

    private void setSysAdminCreateCommunityPanel() {
        txtCommunityName.setText(hospital.getCommunity());
        txtHospitalId.setText(hospital.getHospitalID());
        txtHospitalName.setText(hospital.getHospitalName());
        txtHospitalAddress.setText(hospital.getHospitalAddress());
    }

    private void resetHospitalData() {
        txtCommunityName.setText("");
        txtHospitalId.setText("");
        txtHospitalName.setText("");
        txtHospitalAddress.setText("");
    }

    private Hospital setHospitalData() {
        String communityName = txtCommunityName.getText();
        String hospitalId = txtHospitalId.getText();
        String hospitalName = txtHospitalName.getText();
        String hospitalAddress = txtHospitalAddress.getText();

        Hospital hospital = new Hospital();
        hospital.setCommunity(communityName);
        hospital.setHospitalID(hospitalId);
        hospital.setHospitalName(hospitalName);
        hospital.setHospitalAddress(hospitalAddress);

        return hospital;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCommunityName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHospitalId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHospitalAddress = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        jLabel1.setText("Community Name");

        txtCommunityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Hospital Id");

        jLabel3.setText("Hospital Name");

        jLabel4.setText("Hospital Address");

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCommunityName, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txtHospitalId)
                            .addComponent(txtHospitalName)
                            .addComponent(txtHospitalAddress)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(createBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHospitalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn)
                    .addComponent(updateBtn))
                .addContainerGap(545, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommunityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityNameActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String hospitalId = txtHospitalId.getText();
        hospitalDirectory.addHospital(setHospitalData());
        JOptionPane.showMessageDialog(this, "New hospital data with hospital id : " + hospitalId + " created");
        resetHospitalData();
        CommunityAdminJFrame.refreshCommunityAdminViewCommunityPanel(hospitalDirectory);
    }//GEN-LAST:event_createBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String hospitalId = txtHospitalId.getText();
        Hospital hospital = setHospitalData();
        int index = 0;
        for (Hospital hosp : hospitalDirectory.getHospitals()) {
            if (hosp.getHospitalID().equals(hospitalId)) {
                hospitalDirectory.updateHospital(hospital, index);
                break;
            }
            index++;
        }
        JOptionPane.showMessageDialog(this, "Existing hospital with hospital id : " + hospitalId + " updated");
        resetHospitalData();
        CommunityAdminJFrame.refreshCommunityAdminViewCommunityPanel(hospitalDirectory);
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCommunityName;
    private javax.swing.JTextField txtHospitalAddress;
    private javax.swing.JTextField txtHospitalId;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
