/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.House;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author siddh
 */
public class Register extends javax.swing.JPanel {
    private PersonDirectory personDirectory;
    
    /**
     * Creates new form Register
     */
    public Register(PersonDirectory personDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
        txtAssCommunity.setVisible(false);
        txtAssHospital.setVisible(false);
        lblAssCommunity.setVisible(false);
        lblAssHospital.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        txtApartmentNumber = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtpersonId = new javax.swing.JTextField();
        txtAssCommunity = new javax.swing.JTextField();
        lblAssCommunity = new javax.swing.JLabel();
        txtAssHospital = new javax.swing.JTextField();
        lblAssHospital = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("First Name");

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "Doctor", "Hospital Admin", "Community Admin" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel2.setText("User Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Password");

        jLabel5.setText("Roletype");

        jLabel6.setText("Apartment Number");

        jLabel7.setText("Community");

        jLabel8.setText("Street Address");

        jLabel9.setText("City");

        jLabel10.setText("Age");

        jLabel11.setText("Phone Number");

        jLabel12.setText("SSN");

        lblAssCommunity.setText("Assigned Community Name");

        lblAssHospital.setText("Assigned Hospital ID");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("REGISTER PAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAssCommunity)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblAssHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtLName, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtApartmentNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpersonId, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtAssHospital)
                                    .addComponent(txtAssCommunity))))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btnRegister))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApartmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpersonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAssCommunity)
                    .addComponent(txtAssCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAssHospital)
                    .addComponent(txtAssHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        Person person = new Person();
        House house = new House();
        
        String firstName = "";
        String lastName = "";
        String userName = "";
        String password = "";
        String streetAddress = "";
        String apartmentNumber = "";
        String community = "";
        String city = "";
        int age = 0;
        Long phoneNumber = 0L;
        Long personId = 0L;
        String assHospital = "";
        String assCommunity = "";
        Boolean flag = true;
        
         if(txtFName.getText().isEmpty() || txtFName.getText().isBlank()){
            flag = false;
        } else { 
            firstName = txtFName.getText();
        }
         
         if(txtLName.getText().isEmpty() || txtLName.getText().isBlank()){
            flag = false;
        } else { 
            lastName = txtLName.getText();
        }
         
        if(txtUserName.getText().isEmpty() || txtUserName.getText().isBlank()){
            flag = false;
        } else { 
            userName = txtUserName.getText();
        }
        
        if(txtPassword.getText().isEmpty() || txtPassword.getText().isBlank()){
            flag = false;
        } else { 
            password = txtPassword.getText();
        }
        
        if(txtStreetAddress.getText().isEmpty() || txtStreetAddress.getText().isBlank()){
            flag = false;
        } else { 
            streetAddress = txtStreetAddress.getText();
        }
        
        if(txtApartmentNumber.getText().isEmpty() || txtApartmentNumber.getText().isBlank()){
            flag = false;
        } else { 
            apartmentNumber = txtApartmentNumber.getText();
        }
        
        if(txtCommunity.getText().isEmpty() || txtCommunity.getText().isBlank()){
            flag = false;
        } else { 
            community = txtCommunity.getText();
        }
        
        if(txtCity.getText().isEmpty() || txtCity.getText().isBlank()){
            flag = false;
        } else { 
            city = txtCity.getText();
        }
        
       
        
        if(validateAge(txtAge.getText()) == null){
            flag = false;
        } else { 
            age = validateAge(txtAge.getText());
        }
        
        if(validatePhoneNumber(txtPhoneNumber.getText()) == null){
            flag = false;
        } else { 
            phoneNumber = validatePhoneNumber(txtPhoneNumber.getText());
        }
        
        String roleType = (String)cmbRole.getSelectedItem();
        
         if(txtAssHospital.getText().isEmpty() && roleType.equalsIgnoreCase("Hospital Admin")){
            flag = false;
        } else { 
            assHospital = txtAssHospital.getText();
        }
         
          if(txtAssCommunity.getText().isEmpty() && roleType.equalsIgnoreCase("Community Admin")){
            flag = false;
        } else { 
            assCommunity = txtAssCommunity.getText();
        }
        
        if(flag == false){
            JOptionPane.showMessageDialog(this, "Please enter all details !");
            clearAllFields();
            return;
        }
        
        for(Person p: personDirectory.getPersons()){
            if(userName.equals(p.getUserName()))
            {
                JOptionPane.showMessageDialog(this, "Person already exists !");
                return;
            }
        }
        
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setUserName(userName);
        person.setPassword(password);
        person.setRoleType(roleType);
        person.setAge(age);
        person.setPhoneNumber(phoneNumber);
        person.setAssCommunity(assCommunity);
        person.setAssHospital(assHospital);
        
        house.setCity(city);
        house.setCountry("USA");
        house.setHouseNumber(apartmentNumber);
        house.setStreet(streetAddress);
        house.setCommunity(community);
        
        person.setHouse(house);
        ArrayList<Person> persons = personDirectory.getPersons();
        persons.add(person);
        personDirectory.setPersons(persons);
        
        JOptionPane.showMessageDialog(this, "Profile successfully added !");
        clearAllFields();
        System.out.println(personDirectory.getPersons().size());
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
        String roleType = (String)cmbRole.getSelectedItem();
        if(roleType == "Hospital Admin"){
            txtAssHospital.setVisible(true);
            lblAssHospital.setVisible(true);
             txtAssCommunity.setVisible(false);
            lblAssCommunity.setVisible(false);
        } else if(roleType == "Community Admin"){
            txtAssCommunity.setVisible(true);
            lblAssCommunity.setVisible(true);
            txtAssHospital.setVisible(false);
            lblAssHospital.setVisible(false);
        } else {
            txtAssCommunity.setVisible(false);
            lblAssCommunity.setVisible(false);
            txtAssHospital.setVisible(false);
            lblAssHospital.setVisible(false);
        }
    }//GEN-LAST:event_cmbRoleActionPerformed

        private Integer validateAge(String age){
        try{
            return Integer.parseInt(age);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid Age!");
            return null;
        }
    }
        
         private Long validatePhoneNumber(String phoneNumber)
    {
        try{
                return Long.parseLong(phoneNumber);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid Phone Number!");
            return null;
        }
        
    }
         private Long validatePersonID(String personId){
        try{
            return Long.parseLong(personId);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid SSN!");
            return null;
        }
    }
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAssCommunity;
    private javax.swing.JLabel lblAssHospital;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtApartmentNumber;
    private javax.swing.JTextField txtAssCommunity;
    private javax.swing.JTextField txtAssHospital;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtpersonId;
    // End of variables declaration//GEN-END:variables

    private void clearAllFields() {
        txtAge.setText("");
        txtApartmentNumber.setText("");
        txtCity.setText("");
        txtCommunity.setText("");
        txtFName.setText("");
        txtLName.setText("");
        txtPassword.setText("");
        txtPhoneNumber.setText("");
        txtStreetAddress.setText("");
        txtUserName.setText("");
        txtAssCommunity.setText("");
        txtAssHospital.setText("");
        txtpersonId.setText("");
        
    }


}
